version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:13.1.4-ce.0'
    restart: always
    hostname: 'git.your.site'
    container_name: gitlab
    depends_on:
      - registry
    environment:
      VIRTUAL_HOST: git.your.site
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: git.your.site
      LETSENCRYPT_EMAIL: admin@your.site
      SSH_PROXY_USER: git
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.your.site'
        registry_external_url 'https://registry.your.site'
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_api_url'] = "http://registry:5000"
    expose:
      - 80
      - 443
      - 22
    ports:
      - '2480:80'
      - '2422:22'
    extra_hosts:
      - "registry.your.site:ThisHostIp"
    volumes:
      - 'nginxproxy_certs:/certs'
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    networks:
      default:
      proxy:

  gitlab-runner:
    image: 'gitlab/gitlab-runner:v13.1.1'
    restart: always
    container_name: gitlab-runner
    depends_on:
      - gitlab
    volumes:
     - '/var/run/docker.sock:/var/run/docker.sock'
     - './runner:/etc/gitlab-runner'
    networks:
      default:

  registry:
    image: registry:2.6.2
    restart: always
    container_name: gitlab-registry
    environment:
      - VIRTUAL_HOST=registry.your.site
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=registry.your.site
      - LETSENCRYPT_EMAIL=admin@your.site
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_SECRET=/auth/htpasswd
    ports:
      - '5000:5000'
    volumes:
      - './registry:/var/lib/registry'
      - './auth:/auth'
    networks:
      default:
      proxy:

volumes:
  nginxproxy_certs:
    external: true    
        
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
  proxy:
    external:
      name: nginx-proxy
